# ==========================================================================
# workflow of cgi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

.job_cgi <- setClass("job_cgi", 
  contains = c("job"),
  representation = representation(
    object = "ANY",
    params = "list",
    plots = "list",
    tables = "list",
    others = "ANY"),
  prototype = prototype(
    pg = "cgi",
    info = c("https://www.haowulab.org/software/makeCGI/index.html"),
    cite = "[@RedefiningCpgWuHa2010]",
    method = "The CpG islands data was downloaded from <http://www.rafalab.org> (generated by R package `makeCGI`)",
    tag = "cpg",
    analysis = "makeCGI CpG Islands 预测"
    ))

job_cgi <- function()
{
  .job_cgi()
}

setMethod("step0", signature = c(x = "job_cgi"),
  function(x){
    step_message("Prepare your data with function `job_cgi`.")
  })

setMethod("step1", signature = c(x = "job_cgi"),
  function(x){
    step_message("")
    return(x)
  })

get_cpgIsland_data <- function(type = c("hg38", "mm10", "rn4"), db = .prefix("cpgIsland", "db"), addInternalJob = T)
{
  dir.create(db, F)
  type <- match.arg(type)
  filename <- paste0("model-based-cpg-islands-", type, ".txt")
  savename <- file.path(db, filename)
  if (!file.exists(savename)) {
    url <- paste0("https://www.haowulab.org/software/makeCGI/", filename)
    e(curl::curl_download(url, savename, F))
  }
  if (addInternalJob) {
    .add_internal_job(.job_cgi())
  }
  ftibble(savename)
}

